import os
import logging
from pathlib import Path
from dotenv import load_dotenv

# Load .env before anything else so LangSmith env vars are available
# before LangChain/LangGraph modules are imported. Import order matters here.
load_dotenv()

from fastapi import FastAPI
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from app.api.blog import router as blog_router

# ── Logging ───────────────────────────────────────────────────────────────────
# One call here configures logging for every module across the project.
# All logger(__name__) instances in agents, services, and api will inherit this.

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(name)s | %(levelname)s | %(message)s"
)

logger = logging.getLogger(__name__)

# ── LangSmith tracing ─────────────────────────────────────────────────────────
# LangSmith is activated purely through environment variables — no code needed
# beyond verifying the keys are present. Every graph run will automatically
# appear at smith.langchain.com with full node-by-node traces.
#
# Required in .env:
#   LANGCHAIN_TRACING_V2=true
#   LANGCHAIN_API_KEY=your_key
#   LANGCHAIN_PROJECT=autonomous-blog-agent

if os.getenv("LANGCHAIN_TRACING_V2") == "true":
    logger.info(
        f"LangSmith tracing enabled — project: "
        f"{os.getenv('LANGCHAIN_PROJECT', 'default')}"
    )
else:
    logger.warning(
        "LangSmith tracing is OFF. "
        "Set LANGCHAIN_TRACING_V2=true in .env to enable observability."
    )


# ── FastAPI app ───────────────────────────────────────────────────────────────

app = FastAPI(
    title="Autonomous Blog Generation Agent",
    description=(
        "A production-grade content generation engine built with LangGraph. "
        "Accepts a topic and returns a fully written blog post with images, "
        "generated by a pipeline of specialized AI agents."
    ),
    version="1.0.0",
    docs_url="/docs",       # Swagger UI at /docs
    redoc_url="/redoc"      # ReDoc UI at /redoc
)

# Allow browser-based frontends to talk to this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(blog_router, prefix="/api/v1")

BASE_DIR = Path(__file__).resolve().parent
STATIC_DIR = BASE_DIR / "static"
GENERATED_IMAGES_DIR = BASE_DIR.parent / "generated_images"

# Serve frontend assets and generated diagrams directly from FastAPI.
if STATIC_DIR.exists():
    app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")

GENERATED_IMAGES_DIR.mkdir(parents=True, exist_ok=True)
app.mount(
    "/generated_images",
    StaticFiles(directory=str(GENERATED_IMAGES_DIR)),
    name="generated_images",
)


@app.get("/", include_in_schema=False)
def serve_ui():
    return FileResponse(STATIC_DIR / "index.html")


# ── Health check ──────────────────────────────────────────────────────────────
# Azure App Service pings this to verify the app is alive.
# Keep it fast — no DB calls, no LLM calls.

@app.get("/health")
def health_check():
    return {
        "status": "healthy",
        "version": "1.0.0",
        "tracing": os.getenv("LANGCHAIN_TRACING_V2", "false")
    }